storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    max_users: 1000

uplinks: {}

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

middlewares:
  audit:
    enabled: false

log:
  type: stdout
  format: pretty
  level: http

listen: 0.0.0.0:4873
